# Site settings
baseURL = "https://lutetium0.github.io/Portfolio/"
languageCode = "en-us"
title = "Claude(Yunxiao) Cai"
theme = "forty"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Enter your disqus shortname to enable comments
disqusShortname = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Claude(Yunxiao) Cai"
  description = "Software Engineer"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Hi, my name is Claude(Yunxiao) Cai"
    subtitle = "Welcome to my portfolio!"
    buttonText = "Projects"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.
    [[params.tiles.showcase]]
      title = "Lontarot"
      subtitle = "2.5D Action Role-Playing Game"
      image = "Lontarot.jpg"
      url = "blogs/lontarot"
    [[params.tiles.showcase]]
      title = "MultiUserSpreadsheet"
      subtitle = "MultiUserSpreadsheet"
      image = "MultiuserSpreadsheet.png"
      url = "blogs/multiuserspreadsheet"
    [[params.tiles.showcase]]
      title = "Fighters"
      subtitle = "2D Dual Player Fighting Game"
      image = "fighters.jpg"
      url = "blogs/fighters"
    [[params.tiles.showcase]]
      title = "FightBackSlime!"
      subtitle = "2D Casual Game"
      image = "slime_title.jpg"
      url = "blogs/slime"
    [[params.tiles.showcase]]
      title = "Clone"
      subtitle = "2D Platformer Game"
      image = "clone_title.jpg"
      url = "blogs/clone"
    [[params.tiles.showcase]]
      title = "The Pill"
      subtitle = "3D Short Animation"
      image = "thepill.jpg"
      url = "blogs/thepill"



  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Footer section
  [params.footer]
    enable = true
    copyright = "Claude(Yunxiao) Cai"

    [[params.footer.social]]
      icon = "fa-linkedin"
      url= "https://www.linkedin.com/in/yunxiao-cai-0693a516b/"
      label = "LinkedIn"
